# Copyright (c) 2015-2025, UT-BATTELLE, LLC
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this
# list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
# this list of conditions and the following disclaimer in the documentation
# and/or other materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its contributors
# may be used to endorse or promote products derived from this software without
# specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.


"""
This template provides an example of a minimal LIVVkit extension.
"""

from livvkit import elements as el

# Don't remove summarize_result...this is used by livvkit.components.validation
# to have the summaries appear on the main LIVVkit output page
from livvext.common import summarize_result as sum_common


def run(name, config):
    """
    Runs the extension.

    Args:
        name: The name of the extension
        config: A dictionary representation of the configuration file

    Returns:
       A LIVVkit page element containing the LIVVkit elements to display on a webpage
    """
    # TODO: Put your analysis here
    element_list = [
        el.Error("Unimplemented test", "This test contains no analysis code!"),
        el.Table(
            title="Sample Table",
            data={"row1": [1, 2, 3], "row2": [4, 5, 6]},
            transpose=True,
        ),
    ]

    return el.Page(
        name,
        config["description"],
        elements=element_list,
    )


def print_summary(summary):
    """
    Print out a summary generated by this module's summarize_result method
    """
    raise NotImplementedError


def summarize_result(result):
    """
    Provides a snapshot of the extension's results to be provided on the
    summary webpage and printed to STDOUT via the print_summary method
    """
    return sum_common(result)


def populate_metadata():
    """
    Generates the metadata needed for the output summary page
    """
    raise NotImplementedError
